apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
spec:
  selector:
    matchLabels:
      app: squid
  replicas: 1
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: ubuntu/squid:latest
        ports:
        - containerPort: 3128
          name: proxy
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: squid-service
spec:
  selector:
    app: squid
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
  type: NodePort

  # kubectl apply -f squid-proxy.yml -n misc
  # kubectl port-forward service/squid-service -n misc 3128:3128
  # To check the deployment readiness use example --> curl GET -x http://localhost:3128 -L http://www.google.com